automation:
  activeProfile: HOME
  profiles:
    # defaults
    # sensors:
    # ---
    # targetRelativeHumidity: 50.0
    # targetTemperatureLivingroom: 18
    #
    # lights:
    # ---
    # lights.colorProfile: DEFAULT_CT_BRI
    HOME:
      activeMotionDetection: true
      activeLightAutomation: true
      sensors:
        targetTemperatureLivingroom: 20.5
      presets:
        ALL:
          lights:
            enabled: false
        LIVINGROOM:
          lights:
            enabled: true
        KITCHEN:
          autoProfileSwitch:
            enabled: true
            visitThreshold: 3
            inTimespanSec: 180
            toProfile: COOKING
    AWAY:
      activeMotionDetection: true
      activeLightAutomation: false
      presets:
        ALL:
          lights:
            enabled: false
    VACATION:
      activeMotionDetection: true
      activeLightAutomation: false
      presets:
        ALL:
          lights:
            enabled: false
    SLEEPING:
      activeMotionDetection: true
      activeLightAutomation: false
      presets:
        ALL:
          lights:
            enabled: false
    COOKING:
      activeMotionDetection: true
      activeLightAutomation: true
      autoHomeProfile: true
      presets:
        ALL:
          lights:
            enabled: false
        LIVINGROOM:
          lights:
            enabled: true
        KITCHEN:
          lights:
            enabled: true
            ignoreSensors: true
    BEDTIME:
      activeMotionDetection: true
      activeLightAutomation: true
      presets:
        ALL:
          lights:
            colorProfile: DEFAULT_CT
            enabled: false
            bri: 60
#        BEDROOM:
#          lights:
#            colorProfile: DEFAULT_CT
#            enabled: true
#            bri: 200

