automation:
  activeProfile: HOME
  profiles:
    # defaults
    # sensors:
    # ---
    # targetRelativeHumidity: 50.0
    # targetTemperatureLivingroom: 18
    #
    # lights:
    # ---
    # lights.colorProfile: DEFAULT_CT_BRI
    HOME:
      activateMotionDetection: true
      activateLightAutomation: true
      sensors:
        targetTemperatureLivingroom: 20.5
      presets:
        ALL:
          lights:
            enabled: false
        LIVINGROOM:
          lights:
            enabled: true
    AWAY:
      activateMotionDetection: true
      activateLightAutomation: false
      presets:
        ALL:
          lights:
            enabled: false
    VACATION:
      activateMotionDetection: true
      activateLightAutomation: false
      presets:
        ALL:
          lights:
            enabled: false
    SLEEPING:
      activateMotionDetection: true
      activateLightAutomation: false
      presets:
        ALL:
          lights:
            enabled: false
    BEDTIME:
      activateMotionDetection: true
      activateLightAutomation: true
      presets:
        ALL:
          lights:
            colorProfile: DEFAULT_CT
            enabled: false
            bri: 60
        BEDROOM:
          lights:
            colorProfile: DEFAULT_CT
            enabled: true
            bri: 200

