# JDK for Raspberry Pi (ARM-Architectur)
# FROM arm64v8/eclipse-temurin:21-jdk-alpine
FROM bellsoft/liberica-openjre-alpine:21

# spring profile
ENV SPRING_PROFILES_ACTIVE=docker

WORKDIR /app

# dependencies
COPY target/tyche-housecontrol.jar /app/tyche-housecontrol.jar
COPY automation-profiles.yml /app/automation-profiles.yml
COPY color-profiles.yml /app/color-profiles.yml
COPY truststore.jks /app/truststore.jks

# example port for Spring-Boot-App
EXPOSE 8080

# run app
ENTRYPOINT ["java", "-jar", "tyche-housecontrol.jar"]