<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Hosts1"
    targetNamespace="urn:dslforum-org:service:Hosts:1"
    xmlns:tns="urn:dslforum-org:service:Hosts:1"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <types>
        <xsd:schema targetNamespace="urn:dslforum-org:service:Hosts:1">
            <xsd:element name="GetHostNumberOfEntries">
                <xsd:complexType/>
            </xsd:element>

            <xsd:element name="GetHostNumberOfEntriesResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="NewHostNumberOfEntries" type="xsd:int"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>

    <message name="GetHostNumberOfEntriesRequest">
        <part name="parameters" element="tns:GetHostNumberOfEntries"/>
    </message>
    <message name="GetHostNumberOfEntriesResponse">
        <part name="parameters" element="tns:GetHostNumberOfEntriesResponse"/>
    </message>

    <portType name="Hosts1PortType">
        <operation name="GetHostNumberOfEntries">
            <input message="tns:GetHostNumberOfEntriesRequest"/>
            <output message="tns:GetHostNumberOfEntriesResponse"/>
        </operation>
    </portType>

    <binding name="Hosts1Binding" type="tns:Hosts1PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetHostNumberOfEntries">
            <soap:operation soapAction="urn:dslforum-org:service:Hosts:1#GetHostNumberOfEntries"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="Hosts1Service">
        <port name="Hosts1Port" binding="tns:Hosts1Binding">
            <soap:address location="http://fritz.box:49000/upnp/control/hosts"/>
        </port>
    </service>
</definitions>