spring:
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  config:
    import: 
      - file:automation-profiles.yml
      - file:color-profiles.yml
  application:
    name: tyche
  data:
    mongodb:
      database: tychedb
      host: localhost
      port: 27017
      
security:
  truststore:
    file: truststore.jks

server:
   port: 8080
   ssl:
     enabled: true
     key-store: ./certs/tls.p12
     key-store-password: pw
     key-store-type: PKCS12

raspberry:
  ip: 1.1.1.1

home:
  lat: -6.501408
  lon: 106.318075

deconz:
  apikey: key
  http:
    port: 80
  restapi:
    lights:
      url: http://${raspberry.ip}:${deconz.http.port}/api/${deconz.apikey}/lights
    sensors:
      url: http://${raspberry.ip}:${deconz.http.port}/api/${deconz.apikey}/sensors
    groups:
      url: http://${raspberry.ip}:${deconz.http.port}/api/${deconz.apikey}/groups
  websocket:
    port: 443
    url: ws://${raspberry.ip}:${deconz.websocket.port}
  endpoints:
    - ${deconz.restapi.light.url}
    - ${deconz.restapi.sensor.url}

meteomatics:
  username: user
  pw: pw
  url: https://api.meteomatics.com

---
spring:
  config:
    import:
      - file:/app/automation-profiles.yml
      - file:/app/color-profiles.yml
  data:
    mongodb:
      database: tychedb
      host: mongodb-4
      port: 27017
      
security:
  truststore:
    file: /app/truststore.jks